---
title: "dataTidying"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
```

to call a function from a specific package 'package_name::function_name(...)'


# Data Cleaning

Read in data file.

```{r}
catch_df <- read.csv(file = 'https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1',stringsAsFactors = FALSE)

head(catch_df)
```


ctrl + shift + m == pipe operator

* remove marginal sum and notes column
* move from wide to long format

```{r}
catch_long <- catch_df %>%
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum) %>% 
  gather(key = "species", value = "catch", -Year, -Region)

head(catch_long)
```

```{r}
catch_cleaned <- catch_long %>% 
  rename(catch_thousands = catch) # %>% 
  # mutate(catch = catch_thousands * 1000)

head(catch_cleaned)
```

```{r}
test_catch <- as.integer(catch_cleaned$catch_thousands)

i <-which(is.na(test_catch) == TRUE)

catch_cleaned[i, ]
```
# Split-Apply-Combine

# Joins


